@startuml OrgAdmin Create Supervisor

skinparam actorStyle awesome
left to right direction
skinparam packageStyle rectangle

actor OrgAdmin
actor Supervisor

rectangle usecase14{
  OrgAdmin-- (Create Supervisor)
  (Create Supervisor) .> (OrgAdmin login) : authentication (email, password)
  (OrgAdmin login) .> (Login successful) : authentication successful
  (Login successful) .> (Supervisor name\nSupervisor email\nSupervisor temporary password\nSupervisor phone number) : authorization
  (Supervisor name\nSupervisor email\nSupervisor temporary password\nSupervisor phone number) .> (Supervisor created) : authorization 
  (OrgAdmin login) .> (Login unsuccessful) : authentication failed
  (Login unsuccessful) .> (Supervisor not created)  
  (Create Supervisor)-- Supervisor
}

@enduml