@startuml OrgAdmin Delete Supervisor

skinparam actorStyle awesome
left to right direction
skinparam packageStyle rectangle

actor OrgAdmin
actor Supervisor

rectangle usecase16{
  OrgAdmin -- (Delete Supervisor)
  (Delete Supervisor) .> (OrgAdmin login) : authentication (jwt)
  (OrgAdmin login) .> (Login successful) : authentication successful
  (Login successful) .> (Supervisor deleted)  
  (OrgAdmin login) .> (Login unsuccessful) : authentication failed
  (Login unsuccessful) .> (Supervisor not deleted)  
  (Delete Supervisor) -- Supervisor
}

@enduml