@startuml Update SuperAdmin

skinparam actorStyle awesome
left to right direction
skinparam packageStyle rectangle

actor SuperAdmin
rectangle usecase2 {
  SuperAdmin -- (Update SuperAdmin)
  (Update SuperAdmin) .> (SuperAdmin name\nSuperAdmin email\nSuperAdmin password) : authorization
  (SuperAdmin name\nSuperAdmin email\nSuperAdmin password) .> (SuperAdmin updated) : authorized
  (SuperAdmin name\nSuperAdmin email\nSuperAdmin password) .> (SuperAdmin not updated) : authorization failed
  (Update SuperAdmin)-- SuperAdmin
}

@enduml