@startuml SuperAdmin Create Organization

skinparam actorStyle awesome
left to right direction
skinparam packageStyle rectangle

actor SuperAdmin
actor OrgAdmin
rectangle usecase3 {
  SuperAdmin-- (Create Organization)
  (Create Organization) .> (SuperAdmin login) : authentication (email, password)
  (SuperAdmin login) .> (Login successful) : authentication successful
  (Login successful) .> (Org number\nOrg name) : authorization
  (Org number\nOrg name) .> (Organization created) : authorization 
  (SuperAdmin login) .> (Login unsuccessful) : authentication failed
  (Login unsuccessful) .> (Organization not created)  
  (Create Organization)-- OrgAdmin
}

@enduml