@startuml SuperAdmin Update Supervisor

skinparam actorStyle awesome
left to right direction
skinparam packageStyle rectangle

actor SuperAdmin
actor Supervisor

rectangle usecase12{
  SuperAdmin-- (Update Supervisor)
  (Update Supervisor) .> (SuperAdmin login) : authentication (email, password)
  (SuperAdmin login) .> (Login successful) : authentication successful
  (Login successful) .> (Supervisor name\nSupervisor email\nSupervisor phone number) : authorization
  (Supervisor name\nSupervisor email\nSupervisor phone number) .> (Supervisor updated) : authorization 
  (SuperAdmin login) .> (Login unsuccessful) : authentication failed
  (Login unsuccessful) .> (Supervisor not updated)  
  (Update Supervisor)-- Supervisor
}

@enduml