@startuml OrgAdmin Update Supervisor

skinparam actorStyle awesome
left to right direction
skinparam packageStyle rectangle

actor OrgAdmin
actor Supervisor

rectangle usecase15{
  OrgAdmin-- (Update Supervisor)
  (Update Supervisor) .> (OrgAdmin login) : authentication (email, password)
  (OrgAdmin login) .> (Login successful) : authentication successful
  (Login successful) .> (Supervisor name\nSupervisor email\nSupervisor phone number) : authorization
  (Supervisor name\nSupervisor email\nSupervisor phone number) .> (Supervisor updated) : authorization 
  (OrgAdmin login) .> (Login unsuccessful) : authentication failed
  (Login unsuccessful) .> (Supervisor not updated)  
  (Update Supervisor)-- Supervisor
}

@enduml