@startuml SuperAdmin Create Organization Admin

skinparam actorStyle awesome
left to right direction
skinparam packageStyle rectangle

actor SuperAdmin
actor OrgAdmin
rectangle usecase6{
  SuperAdmin-- (Create OrgAdmin)
  (Create OrgAdmin) .> (SuperAdmin login) : authentication (email, password)
  (SuperAdmin login) .> (Login successful) : authentication successful
  (Login successful) .> (OrgAdmin name\nOrgAdmin email\nOrgAdmin temporary password\nOrgAdmin phone number\nOrgAdmin organization) : authorization
  (OrgAdmin name\nOrgAdmin email\nOrgAdmin temporary password\nOrgAdmin phone number\nOrgAdmin organization) .> (OrgAdmin created) : authorization 
  (SuperAdmin login) .> (Login unsuccessful) : authentication failed
  (Login unsuccessful) .> (OrgAdmin not created)  
  (Create OrgAdmin)-- OrgAdmin
}

@enduml