@startuml SuperAdmin Delete Organization Admin

skinparam actorStyle awesome
left to right direction
skinparam packageStyle rectangle

actor SuperAdmin

rectangle usecase9{
  SuperAdmin -- (Delete OrgAdmin)
  (Delete OrgAdmin) .> (SuperAdmin login)
  (SuperAdmin login) --> (Login successful) 
  (Login successful) .> (OrgAdmin deleted)
  (SuperAdmin login) .> (Login unsuccessful) 
  (Login unsuccessful) .> (OrgAdmin not deleted)  
  (Delete OrgAdmin)
}

@enduml