@startuml SuperAdmin Create Issue

skinparam actorStyle awesome
left to right direction
skinparam packageStyle rectangle

actor SuperAdmin
actor OrgAdmin

rectangle usecase1 {
  SuperAdmin-- (Create Issue)
  (Create Issue) .> (SuperAdmin login) : authentication (email, password)
  (SuperAdmin login) .> (Login successful) : authentication successful
  (Login successful) .> (Issue number\nIssue message\nSuperadmin location) : authorization
  (Issue number\nIssue message\nSuperadmin location) .> (Issue created) : authorization 
  (SuperAdmin login) .> (Login unsuccessful) : authentication failed
  (Login unsuccessful) .> (Issue not created)  
  (Create Issue)-- OrgAdmin
}

@enduml