@startuml Manager Resolve Issue

skinparam actorStyle awesome
left to right direction
skinparam packageStyle rectangle

actor Manager
actor OrgAdmin

rectangle usecase4 {
  Manager -- (Resolve Issue)
  (Resolve Issue) .> (Manager login) : authentication (email, password)
  (Manager login) .> (Login successful) : authentication successful
  (Login successful) .> (Issue number\nIssue message\nStatus) : authorization
  (Issue number\nIssue message\nStatus) .> (Issue resolved) : authorization  
  (Manager login) .> (Login unsuccessful) : authentication failed
  (Login unsuccessful) .> (Issue pending)  
  (Resolve Issue)-- OrgAdmin
}

@enduml