@startuml Manager Create Issue

skinparam actorStyle awesome
left to right direction
skinparam packageStyle rectangle

actor Manager
actor Supervisor

rectangle usecase5{
  Manager-- (Create Issue)
  (Create Issue) .> (Manager login) : authentication (email, password)
  (Manager login) .> (Login successful) : authentication successful
  (Login successful) .> (Issue number\nIssue message\nSuperadmin location) : authorization
  (Issue number\nIssue message\nSuperadmin location) .> (Issue created) : authorization 
  (Manager login) .> (Login unsuccessful) : authentication failed
  (Login unsuccessful) .> (Issue not created)  
  (Create Issue)-- Supervisor
}

@enduml