@startuml AllUseCases

participant "SuperAdmin" as SuperAdmin
SuperAdmin -> SuperAdmin:Create SuperAdmin (UC1)
SuperAdmin -> SuperAdmin:Update SuperAdmin (UC2)

SuperAdmin -> OrgAdmin:Create Organization (UC3)
SuperAdmin -> OrgAdmin:Enable Organization (UC4)
SuperAdmin -> OrgAdmin:Disable Organization (UC5)

SuperAdmin -> OrgAdmin:Create Organization Admin (UC6)
SuperAdmin -> OrgAdmin:Update Organization Admin (UC7)

OrgAdmin -> OrgAdmin:First Time Login (UC8)
OrgAdmin -> OrgAdmin:OrgAdmin update profile (UC9)
OrgAdmin -> OrgAdmin:OrgAdmin update organization (UC10)

SuperAdmin -> OrgAdmin:Create issue (UC10)
SuperAdmin -> SuperAdmin:Create issue (UC5)

OrgAdmin -> SuperAdmin:Create issue (UC6)

OrgAdmin -> Supervisor:Create Supervisor (UC7)
OrgAdmin -> Manager:Create Manager (UC8)
OrgAdmin -> User:Create User (UC9)

OrgAdmin -> Supervisor:Create issue (UC10)
OrgAdmin -> OrgAdmin:Create issue (UC11)

participant "Supervisor" as Supervisor
Supervisor -> OrgAdmin:Create issue (UC12)
Supervisor -> Manager:Create issue (UC13)
Supervisor -> Supervisor:Create issue (UC14)


participant "Manager" as Manager
Manager -> Supervisor:Create issue (UC15)
Manager -> User:Create issue (UC16)
Manager -> Manager:Create issue (UC17)


participant "User" as User
User -> Manager:Create issue (UC18)
User -> User:Create issue (UC19)


@enduml