@startuml AllUseCases

participant "SuperAdmin" as SuperAdmin
SuperAdmin -> SuperAdmin:Create SuperAdmin (UC1)
SuperAdmin -> SuperAdmin:Update SuperAdmin (UC2)

SuperAdmin -> OrgAdmin:Create Organization (UC3)
SuperAdmin -> OrgAdmin:Enable Organization (UC4)
SuperAdmin -> OrgAdmin:Disable Organization (UC5)

SuperAdmin -> OrgAdmin:Create Organization Admin (UC6)
SuperAdmin -> OrgAdmin:Update Organization Admin (UC7)

OrgAdmin -> OrgAdmin:OrgAdmin first time Login (UC8)
OrgAdmin -> OrgAdmin:OrgAdmin update profile (UC9)
OrgAdmin -> OrgAdmin:OrgAdmin update organization (UC10)

OrgAdmin -> Manager:Create Manager (UC11)
OrgAdmin -> Manager:Update Manager (UC12)
OrgAdmin -> Manager:Delete Manager (UC13)

OrgAdmin -> Supervisor:Create Supervisor (UC14)
OrgAdmin -> Supervisor:Update Supervisor (UC15)
OrgAdmin -> Supervisor:Delete Supervisor (UC16)

OrgAdmin -> User:Create User (UC17)
OrgAdmin -> User:Update User (UC18)
OrgAdmin -> User:Delete User (UC19)

Supervisor -> Supervisor:Supervisor first time login (UC20)
Supervisor -> Supervisor:Supervisor update profile (UC21)

Manager -> Manager:Manager first time login (UC22)
Manager -> Manager:Manager update profile (UC23)

User -> User:User first time login (UC24)
User -> User:Supervisor update profile (UC25)

@enduml